/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "timesync.h"
#include <errno.h>

void
timing_prog_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	char *timing_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TIMING_PROG, TIMING_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	// START TIMER
	struct timeval b4;
	gettimeofday(&b4, NULL);
	double b4_in_mill = (b4.tv_sec) * 1000 + (b4.tv_usec) / 1000 ; 
	//BLOCK CALL
	result_1 = timing_1((void*)&timing_1_arg, clnt);
	// END TIMER
	struct timeval after;
	gettimeofday(&after, NULL);
	double after_in_mill = (after.tv_sec) * 1000 + (after.tv_usec) / 1000 ;


	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("ROUND TRIP TIME: %f \n", after_in_mill - b4_in_mill );
		double servertime = *result_1;
		printf("Got timeval from server: %f \n", servertime);
		double time_to_add = (after_in_mill - b4_in_mill ) / 2.0; 
		double sec_to_add = floor(time_to_add / 1000); 
		double usec_to_add = (time_to_add - (sec_to_add * 1000)) * 1000;

		double server_sec = floor(servertime/ 1000); 
		double server_usec  = (servertime - (server_sec * 1000)) * 1000;


		long  adjusted_seconds = (long) (server_sec + sec_to_add);
		long  adjusted_usec    = (long) (server_usec + usec_to_add);

		struct timeval newTime;

		newTime.tv_sec = adjusted_seconds;
		newTime.tv_usec = adjusted_usec;
		int rc = settimeofday(&newTime  , NULL);

		if(rc==0) {
    		    printf("settimeofday() successful.\n");
    		}
    		else {
        		printf("settimeofday() failed, "
		        "errno = %d\n",errno);
		        return;
    		}	
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	timing_prog_1 (host);
exit (0);
}
