/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "timesync.h"

double *
timing_1_svc(void *argp, struct svc_req *rqstp)
{
	static double  result;
	printf("Hit! \n");
	struct timeval b4;
	gettimeofday(&b4, NULL);
	double b4_in_mill = (b4.tv_sec) * 1000 + (b4.tv_usec) / 1000 ; 

	result = b4_in_mill;
	return &result;
}
