/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TIMESYNC_H_RPCGEN
#define _TIMESYNC_H_RPCGEN

#include <rpc/rpc.h>
#include <math.h>
#include <stdio.h>
#include <sys/time.h>
#include <time.h>


#ifdef __cplusplus
extern "C" {
#endif


#define TIMING_PROG 0x23451111
#define TIMING_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define timing 1
extern  double * timing_1(void *, CLIENT *);
extern  double * timing_1_svc(void *, struct svc_req *);
extern int timing_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define timing 1
extern  double * timing_1();
extern  double * timing_1_svc();
extern int timing_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TIMESYNC_H_RPCGEN */
